// Canonical decomposition (full NFD) and canonical combining class lookup,
// backed by the nfd.bin resource generated by GenNormData from ICU's
// norm2/nfc.txt. Hangul syllables are decomposed arithmetically.
//
// Container format is provisional (sorted arrays + binary search); see
// Docs/04-milestone-plan.md, cross-cutting decision 1.

import Foundation

public struct NormalizationData: Sendable {
    /// (scalar << 8) | ccc, sorted by scalar.
    let cccEntries: [UInt32]
    /// (scalar << 32) | (bufferOffset << 8) | length, sorted by scalar.
    let decompEntries: [UInt64]
    let buffer: [UInt32]

    public enum ParseError: Error {
        case tooShort
        case badMagic
        case unsupportedVersion(UInt32)
    }

    public init(contentsOf url: URL) throws {
        let bytes = [UInt8](try Data(contentsOf: url))
        var pos = 0
        func u32() throws -> UInt32 {
            guard pos + 4 <= bytes.count else { throw ParseError.tooShort }
            defer { pos += 4 }
            return UInt32(bytes[pos]) | (UInt32(bytes[pos + 1]) << 8)
                | (UInt32(bytes[pos + 2]) << 16) | (UInt32(bytes[pos + 3]) << 24)
        }
        guard try u32() == 0x4446_4e53 else { throw ParseError.badMagic }  // "SNFD"
        let version = try u32()
        guard version == 1 else { throw ParseError.unsupportedVersion(version) }

        var ccc = [UInt32](repeating: 0, count: Int(try u32()))
        for i in 0..<ccc.count { ccc[i] = try u32() }
        cccEntries = ccc

        var decomp = [UInt64](repeating: 0, count: Int(try u32()))
        for i in 0..<decomp.count {
            let lo = try u32()
            let hi = try u32()
            decomp[i] = UInt64(lo) | (UInt64(hi) << 32)
        }
        decompEntries = decomp

        var buf = [UInt32](repeating: 0, count: Int(try u32()))
        for i in 0..<buf.count { buf[i] = try u32() }
        buffer = buf
    }

    /// The bundled normalization data (Unicode 17, from ICU's nfc.txt).
    public static func standard() throws -> NormalizationData {
        guard let url = Bundle.module.url(forResource: "nfd", withExtension: "bin") else {
            throw ParseError.tooShort
        }
        return try NormalizationData(contentsOf: url)
    }

    // MARK: Lookup

    /// Canonical combining class of a scalar.
    @inline(__always)
    func ccc(_ c: UInt32) -> UInt8 {
        if c < 0x300 { return 0 }  // fast path: below the first combining mark
        // Binary search for (c << 8) in the high 24 bits.
        var lo = 0
        var hi = cccEntries.count
        while lo < hi {
            let mid = (lo + hi) / 2
            if cccEntries[mid] >> 8 < c { lo = mid + 1 } else { hi = mid }
        }
        if lo < cccEntries.count && cccEntries[lo] >> 8 == c {
            return UInt8(truncatingIfNeeded: cccEntries[lo])
        }
        return 0
    }

    /// True if `c` has a canonical decomposition (including Hangul syllables).
    @inline(__always)
    func hasDecomposition(_ c: UInt32) -> Bool {
        if c < 0xc0 { return false }
        if (0xac00...0xd7a3).contains(c) { return true }
        var lo = 0
        var hi = decompEntries.count
        while lo < hi {
            let mid = (lo + hi) / 2
            if decompEntries[mid] >> 32 < UInt64(c) { lo = mid + 1 } else { hi = mid }
        }
        return lo < decompEntries.count && decompEntries[lo] >> 32 == UInt64(c)
    }

    /// Appends the full canonical decomposition of `c` to `out`.
    /// Returns false if `c` has no decomposition (nothing appended).
    @inline(__always)
    func appendDecomposition(of c: UInt32, to out: inout [UInt32]) -> Bool {
        if c < 0xc0 { return false }  // fast path: no decompositions below U+00C0
        if (0xac00...0xd7a3).contains(c) {
            // Hangul syllable: arithmetic decomposition to L V (T) Jamo.
            let sIndex = Int(c) - 0xac00
            out.append(UInt32(0x1100 + sIndex / 588))
            out.append(UInt32(0x1161 + (sIndex % 588) / 28))
            let t = sIndex % 28
            if t != 0 { out.append(UInt32(0x11a7 + t)) }
            return true
        }
        var lo = 0
        var hi = decompEntries.count
        while lo < hi {
            let mid = (lo + hi) / 2
            if decompEntries[mid] >> 32 < UInt64(c) { lo = mid + 1 } else { hi = mid }
        }
        guard lo < decompEntries.count && decompEntries[lo] >> 32 == UInt64(c) else { return false }
        let entry = decompEntries[lo]
        let offset = Int((entry >> 8) & 0xff_ffff)
        let length = Int(entry & 0xff)
        out.append(contentsOf: buffer[offset..<(offset + length)])
        return true
    }
}
