// Canonical decomposition (full NFD) and canonical combining class lookup, backed by the nfd.bin resource generated by GenNormData from ICU's norm2/nfc.txt. Hangul syllables are decomposed arithmetically.
//
// Single-trie format (the ICU4X model, nfd.bin v2): one lookup per scalar — a flat index of deduplicated 64-value blocks — yields a packed value with ccc (bits 0..7), lead ccc (8..15), decomposition length (16..18; 7 = Hangul sentinel) and buffer offset (19..31). Value 0 means inert: ccc 0, no decomposition. Layout details in Sources/GenNormData/main.swift.

import Foundation

// @unchecked: the buffer views are immutable after init and their memory is owned by `storage`, which the struct retains.
public struct NormalizationData: @unchecked Sendable {
    /// Owns the memory behind the buffer views below.
    let storage: DataStorage
    /// Block number per 64-scalar range (0..<0x110000 covered).
    let index: UnsafeBufferPointer<UInt16>
    /// Packed per-scalar values, in blocks of 64.
    let data: UnsafeBufferPointer<UInt32>
    /// Decomposition scalars, referenced by the values' offset/length.
    let buffer: UnsafeBufferPointer<UInt32>

    public enum ParseError: Error {
        case tooShort
        case badMagic
        case unsupportedVersion(UInt32)
    }

    public init(contentsOf url: URL) throws {
        let bytes = [UInt8](try Data(contentsOf: url))
        var pos = 0
        func u32() throws -> UInt32 {
            guard pos + 4 <= bytes.count else { throw ParseError.tooShort }
            defer { pos += 4 }
            return UInt32(bytes[pos]) | (UInt32(bytes[pos + 1]) << 8)
                | (UInt32(bytes[pos + 2]) << 16) | (UInt32(bytes[pos + 3]) << 24)
        }
        func u16() throws -> UInt16 {
            guard pos + 2 <= bytes.count else { throw ParseError.tooShort }
            defer { pos += 2 }
            return UInt16(bytes[pos]) | (UInt16(bytes[pos + 1]) << 8)
        }
        guard try u32() == 0x4446_4e53 else { throw ParseError.badMagic }  // "SNFD"
        let version = try u32()
        guard version == 2 else { throw ParseError.unsupportedVersion(version) }

        let storage = DataStorage()
        self.storage = storage

        var idx = [UInt16](repeating: 0, count: Int(try u32()))
        for i in 0..<idx.count { idx[i] = try u16() }
        var dat = [UInt32](repeating: 0, count: Int(try u32()))
        for i in 0..<dat.count { dat[i] = try u32() }
        var buf = [UInt32](repeating: 0, count: Int(try u32()))
        for i in 0..<buf.count { buf[i] = try u32() }

        // Validate once so the unchecked reads below stay in bounds for every scalar (0...0x10FFFF) and every stored offset/length.
        guard idx.count == 0x110000 >> 6,
              dat.count % 64 == 0,
              idx.allSatisfy({ (Int($0) << 6) + 63 < dat.count }),
              dat.allSatisfy({ v in
                  let length = Int((v >> 16) & 7)
                  return length == 0 || length == 7
                      || Int(v >> 19) + length <= buf.count
              })
        else { throw ParseError.tooShort }

        index = storage.store(idx)
        data = storage.store(dat)
        buffer = storage.store(buf)
    }

    /// The bundled normalization data (Unicode 17, from ICU's nfc.txt).
    public static func standard() throws -> NormalizationData {
        guard let url = Bundle.module.url(forResource: "nfd", withExtension: "bin") else {
            throw ParseError.tooShort
        }
        return try NormalizationData(contentsOf: url)
    }

    /// Trivial (ARC-free) view of the trie for hot paths that must not retain the storage (see CollationDataView for the rationale).
    var view: NormalizationDataView {
        NormalizationDataView(index: index, data: data)
    }

    // MARK: Lookup

    /// The packed trie value for a scalar (see the header comment).
    @inline(__always)
    func value(_ c: UInt32) -> UInt32 {
        data[(Int(index[Int(c >> 6)]) << 6) | Int(c & 63)]
    }

    /// True if `c` is normalization-inert: ccc 0 and no decomposition. The NFD fast path for bare starters.
    @inline(__always)
    func isInert(_ c: UInt32) -> Bool {
        c < 0xc0 || value(c) == 0
    }

    /// Canonical combining class of a scalar.
    @inline(__always)
    func ccc(_ c: UInt32) -> UInt8 {
        if c < 0x300 { return 0 }  // fast path: below the first combining mark
        return UInt8(truncatingIfNeeded: value(c))
    }

    /// True if `c` has a canonical decomposition (including Hangul syllables).
    @inline(__always)
    func hasDecomposition(_ c: UInt32) -> Bool {
        c >= 0xc0 && (value(c) >> 16) & 7 != 0
    }

    /// Canonical combining class of the first scalar of `c`'s full decomposition (`c`'s own ccc if it has none) — "lccc". Nonzero means the NFD form of text starting at `c` can depend on what precedes it (canonical reordering may move the lead mark across the boundary).
    @inline(__always)
    func leadCCC(_ c: UInt32) -> UInt8 {
        if c < 0xc0 { return 0 }
        return UInt8(truncatingIfNeeded: value(c) >> 8)
    }

    /// Appends the full canonical decomposition of `c` to `out`. Returns false if `c` has no decomposition (nothing appended).
    @inline(__always)
    func appendDecomposition(of c: UInt32, to out: inout [UInt32]) -> Bool {
        if c < 0xc0 { return false }  // fast path: no decompositions below U+00C0
        let v = value(c)
        let length = Int((v >> 16) & 7)
        if length == 0 { return false }
        if length == 7 {
            // Hangul syllable: arithmetic decomposition to L V (T) Jamo.
            let sIndex = Int(c) - 0xac00
            out.append(UInt32(0x1100 + sIndex / 588))
            out.append(UInt32(0x1161 + (sIndex % 588) / 28))
            let t = sIndex % 28
            if t != 0 { out.append(UInt32(0x11a7 + t)) }
            return true
        }
        let offset = Int(v >> 19)
        out.append(contentsOf: buffer[offset..<(offset + length)])
        return true
    }

    /// Number of scalars in the fully expanded canonical decomposition of `c` — 0 when `c` has none. Count-only twin of `appendDecomposition` plus the one-level recursion buildNFDSourceMap applied over its output (the pool is fully decomposed in practice, so the second level is defensive parity, not extra data). Keep in lockstep with `appendDecomposition` — the NFD→source map's entry counts must equal the scalars the NFD pipeline actually emits.
    func fullDecompositionCount(of c: UInt32) -> Int {
        if c < 0xc0 { return 0 }
        let v = value(c)
        let length = Int((v >> 16) & 7)
        if length == 0 { return 0 }
        if length == 7 {
            // Hangul syllable: L V (T) Jamo; Jamo decompose no further.
            return (Int(c) - 0xac00) % 28 != 0 ? 3 : 2
        }
        let offset = Int(v >> 19)
        var n = 0
        for d in buffer[offset..<(offset + length)] {
            if d >= 0xc0 {
                let dv = value(d)
                let dlength = Int((dv >> 16) & 7)
                if dlength == 0 {
                    n += 1
                } else if dlength == 7 {
                    n += (Int(d) - 0xac00) % 28 != 0 ? 3 : 2
                } else {
                    n += dlength
                }
            } else {
                n += 1
            }
        }
        return n
    }

    /// Quick decomposition for the common Latin case: a precomposed character that decomposes to exactly [starter, one-combining-mark]. Returns the two scalars directly from one trie lookup, or nil if the decomposition is longer, the lead scalar is a non-starter, or the character has no decomposition. Allows NFDIterator to skip the full refill machinery.
    @inline(__always)
    func quickDecomp(_ c: UInt32) -> (base: UInt32, mark: UInt32)? {
        let v = value(c)
        let length = Int((v >> 16) & 7)
        guard length == 2 else { return nil }
        let offset = Int(v >> 19)
        let base = buffer[offset]
        let mark = buffer[offset + 1]
        // Only valid if the base is a starter (ccc=0) and the mark has ccc>0. For length-2 Latin decompositions this is always true, but check to be safe against exotic cases.
        guard ccc(base) == 0, ccc(mark) != 0 else { return nil }
        return (base, mark)
    }
}

/// Trivial view of the normalization trie: the lookups the byte fast path's safety check needs, with no reference counting on capture. The owning NormalizationData must outlive it.
struct NormalizationDataView {
    let index: UnsafeBufferPointer<UInt16>
    let data: UnsafeBufferPointer<UInt32>

    /// See NormalizationData.leadCCC.
    @inline(__always)
    func leadCCC(_ c: UInt32) -> UInt8 {
        if c < 0xc0 { return 0 }
        return UInt8(truncatingIfNeeded: data[(Int(index[Int(c >> 6)]) << 6) | Int(c & 63)] >> 8)
    }
}
